---
title: "FP_analysis"
author: "Umesh/Suman"
date: "12/5/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

  ```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
#Import and view data
fp <- read.csv("D:/Edrive/HTRP_Binod_sir/data/fp.csv")
dim(fp)
fp<- as.data.frame(fp)
typeof(fp)
library(tidyverse)
library(psych)
View(fp)
```

```{r}
#Include data with overall score 7 only
fp <- fp %>%
  filter(scoreall == 7 & respondentagree == 1)

dim(fp)
```
```{r}
fp %>%
  group_by(province) %>%
  ggplot(aes(clusterno, district)) +
  geom_col()

```



```{r}
#Summary statistics  Overall: TO be added while running final test to avoid knit time

```

```{r}
#Description of sociodemographic variables

# Location

#Province
fp$provi <- as.factor(fp$province)
typeof(fp$province)
levels(fp[,"province"])
fp$province = factor(fp$province, labels=c("Province 1", "Province 2", "Bagmati", "Gandaki", "Lumbini", "Karnali","Susurpaschim"))
typeof(fp$province)
levels(fp[,"province"])

fp%>%
  group_by(province) %>%
  count() %>%
  mutate (percent =n/nrow(fp) *100)
```

```{r}
fp %>% 
count((district), sort = T)
```




```{r}
#district
fp$district <- as.factor(fp$district)
typeof(fp$district)
levels(fp[,"district"])
# fp$district = factor(fp$district, labels=c("jhapa", "bara", "lalitpur", "syangja","kapilbastu","pyuthan", "dailekh", "achham", "kailali"))
typeof(fp$district)
levels(fp[,"district"])

fp%>%
  group_by(district) %>%
  count() %>%
  mutate (percent =n/nrow(fp) *100)

#local level
fp$locallvlname <- as.factor(fp$locallvlname)
typeof(fp$locallvlname)
levels(fp[,"locallvlname"])


fp%>%
  group_by(locallvlname) %>%
  count() %>%
  mutate (percent =n/nrow(fp) *100)

#clusternumber
fp$clusterno <- as.factor(fp$clusterno)
typeof(fp$clusterno)
levels(fp[,"clusterno"])
```

```{r}
fp$q105 <- factor(as.numeric(fp$q105), levels = c( '1', '2', '3', '4'), labels = c( "Rural", "Urban", "Sub-metro", "Metro"))

```


```{r}
fp%>%
  group_by(clusterno) %>%
  count((clusterno), sort = T)%>%
  mutate (percent =n/nrow(fp) *100) %>% 
  ggplot(aes(clusterno, percent))+
  geom_col()


```
```{r}
fp %>%
  filter(!is.na(district)) %>%
  ggplot(aes(clusterno, hhno, fill =  province))+
  geom_col()+
  coord_flip()
```

```{r}
# Type of local level
fp <- fp %>%
  mutate(typeoflocal = ifelse(locallvlname == "aathbis"|locallvlname == "chapakot"|locallvlname == "panchadewal"|locallvlname == "bhajani"|locallvlname == "maharajganj", "Municipality", 
                              ifelse(locallvlname == "lalitpur", "Metropolitan city", "Rural Municipality")))
     
#Urbanrural
  fp <- fp %>%
  mutate(typeoflocal1 = ifelse(locallvlname == "aathbis"|locallvlname == "chapakot"|locallvlname == "panchadewal"|locallvlname == "bhajani"|locallvlname == "maharajganj"|locallvlname == "lalitpur", "Urban", "Rural"))

fp$typeoflocal

fp$typeoflocal <- as.factor(fp$typeoflocal)
typeof(fp$typeoflocal)
levels(fp[,"typeoflocal"])


fp%>%
  group_by(typeoflocal) %>%
  count() %>%
  mutate (percent =n/nrow(fp) *100)

```

```{r}
#Religion q107
fp$q107<- factor(fp$q107)
typeof(fp$q107)
levels(fp[,"q107"])

fp$q107 <- factor(as.numeric(fp$q107), levels = c( '1', '2', '3', '4', '5'), labels = c( "Hindu", "Buddhist", "Muslim", "Kirnat", "Christian"))

fp%>%
  group_by(q107) %>%
  count() %>%
  mutate (percent =n/nrow(fp) *100)
```


```{r}
fp$respcastecode<- as.factor(fp$respcastecode)
typeof(fp$respcastecode)
levels(fp[,"respcastecode"])

fp$respcastecode <- factor(as.numeric(fp$respcastecode), levels = c( "1", "2", "3", "4", "5" ,"6", "7", "8", "9", "10","11"), labels = c( "Hill Brahmin", "Hill Chhettri", "Tarai Brahmin/Chhettri", "Other Tarai Caste", "Hill Dalit", "Tarai Dalit", "Newar", "Hill Janajati", "Tarai Janajati"," Muslim", "Others"))

fp%>%
  group_by(respcastecode) %>%
  count() %>%
  mutate (percent =n/nrow(fp) *100)

```
```{r}
#Age of respondent q109
typeof(fp$q109) 
fp$q109 <- as.numeric(fp$q109)
typeof(fp$q109)

hist(fp$q109)

fp%>%
  group_by(q109) %>%
  count()

# Creating age groups
fp <- fp %>%
  mutate(agegroup = ifelse (q109>14 & q109<20, "15-19", 
                            ifelse(q109>19 & q109<25, "20-24",
                                   ifelse(q109 >24 & q109 <30, "25-29",
                                          ifelse(q109 > 29 & q109 <35, "30-34",
                                                 ifelse(q109 >34 & q109 <40, "35-39",
                                                        ifelse (q109 >39 & q109 <45,"40-44", "45-49")))))))
fp$agegroup

fp%>%
  group_by(agegroup) %>%
  count() %>%
  mutate (percent =n/nrow(fp) *100)
```


```{r}
#Age at marriage q110
typeof(fp$q110)
fp$q110 <- as.numeric(fp$q110)
typeof(fp$q110)


fp%>%
  group_by(q110) %>%
  count()

# Creating age groups
fp <- fp %>%
  mutate(ageatmarriagegroup = (ifelse(q110<15, "14 or less", 
                                      ifelse( q110>14 & q110<20, "15-19", 
                                              ifelse(q110>19 & q110<25, "20-24",
                                                     ifelse(q110 >24 & q110 <30, "25-29",
                                                            ifelse(q110 > 29 & q110 <35, "30-34",
                                                                   ifelse(q110 >34 & q110 <40, "35-39",
                                                                          ifelse (q110 >39 & q110 <45,"40-44", "45-49")))))))))
```


```{r}
fp%>%
  group_by(ageatmarriagegroup) %>%
  count() %>%
  mutate (percent =n/nrow(fp) *100)
```


```{r}
#HTRP Group of respondents

#Extract cols from file
fp$adolescent = as.numeric(fp$adolescent)
fp$young = as.numeric(fp$young)
fp$rural = as.numeric(fp$rural)
fp$hilldalit = as.numeric(fp$hilldalit)
fp$taraidalit = as.numeric(fp$taraidalit)
fp$muslim = as.numeric(fp$muslim)
fp$slum = as.numeric(fp$slum)
fp$geoghtrp = as.numeric(fp$geoghtrp)
fp$disabled = as.numeric(fp$disabled)

#Select the columns
htrpgrp = data.frame(fp$adolescent, fp$young, fp$rural, fp$hilldalit, fp$taraidalit,fp$muslim, fp$slum, fp$geoghtrp, fp$disabled)
nrow(htrpgrp)
```


```{r}
#Get the rows having at least 1 response
htrpgrp1 = subset(fp, fp$adolescent== 1 | fp$young == 1 |fp$rural ==1 | fp$hilldalit ==1 | fp$taraidalit == 1 |fp$muslim == 1| fp$slum == 1 | fp$geoghtrp == 1 | fp$disabled == 1)

#Add the sum of column (cases)
c=colSums(htrpgrp)
c
#Add the total number of responses 
fp %>% 
fp$s=sum(htrpgrp)
s

#NUmber of rows with at least one response
n=nrow(htrpgrp1)
n

a=round(c/n*100,2) #Percent of Cases
a #Percent of Cases
b=round(c/s*100,2) # Percent of Responses
b

barplot(a) #Cases
barplot(b) # Responses
```

```{r}
#Main job of respondent q112
fp$q112<- as.factor(fp$q112)
typeof(fp$q112)
levels(fp[,"q112"])

fp$q112 <- factor(as.numeric(fp$q112), levels = c( '1', '2', '3', '4', '5', "6", "7", "8"), labels = c( "Housewife", "Agriculture", "Government service", "Private job", "Daily wage","Business", "Foreign employment", "Others"))


fp%>%
  group_by(q112) %>%
  count() %>%
  mutate (percent =n/nrow(fp) *100)
```

```{r}
#Main job of respondent's husband q113
fp$q113<- as.factor(fp$q113)
typeof(fp$q113)
levels(fp[,"q113"])

fp$q113 <- factor(as.numeric(fp$q113), levels = c( '1', '2', '3', '4', '5', "6", "7"), labels = c( "Agriculture", "Government service", "Private job", "Daily wage labourer","Business", "Foreign employment", "Others"))


fp%>%
  group_by(q113) %>%
  count() %>%
  mutate (percent =n/nrow(fp) *100)
```

```{r}
#
```


```{r}
#Respondent's Literacy and education  q114
fp$q114<- as.factor(fp$q114)
typeof(fp$q114)
levels(fp[,"q114"])

fp$q114 <- factor(as.numeric(fp$q114), levels = c( '1', '2'), labels = c("Literate", "Illiterate"))


fp%>%
  group_by(q114) %>%
  count() %>%
  mutate (percent =n/nrow(fp) *100)

#Respondent's education

fp$respedun <- as.numeric(fp$respedun)
describe(fp$respedun)
```


```{r}
#Respondent's husbands' Literacy and education  q114
fp$q116<- as.factor(fp$q116)
typeof(fp$q116)
levels(fp[,"q116"])

fp$q116 <- factor(as.numeric(fp$q116), levels = c( '1', '2'), labels = c("Literate", "Illiterate"))


fp%>%
  group_by(q116) %>%
  count() %>%
  mutate (percent =n/nrow(fp) *100)

#Respondent's education q117

fp$respedun <- as.numeric(fp$q117)
describe(fp$respedun)
```


```{r}
#Age of respondent's husband q118
typeof(fp$q118) 
fp$q118 <- as.numeric(fp$q118)
typeof(fp$q118)
describe(fp$q118)
hist(fp$q118)

fp%>%
  group_by(q118) %>%
  count()

# Creating age groups
fp <- fp %>%
  mutate(husagegroup = ifelse (q118 < 15, "14 or less", ifelse(q118>14 & q118<20, "15-19", 
                                                               ifelse(q118>19 & q118<25, "20-24",
                                                                      ifelse(q118 >24 & q118 <30, "25-29",
                                                                             ifelse(q118 > 29 & q118 <35, "30-34",
                                                                                    ifelse(q118 >34 & q118 <40, "35-39",
                                                                                           ifelse (q118 >39 & q118<45,"40-44",
                                                                                                   ifelse(q118>44 & q118<50, "45-49", "50+")))))))))

fp$husagegroup

fp%>%
  group_by(husagegroup) %>%
  count() %>%
  mutate (percent =n/nrow(fp) *100)
```
```{r}
#Spousal age difference
fp <- fp%>%
  mutate(spousalagediff = q118-q109)

fp$spousalagediff < as.numeric(fp$spousalagediff)

describe(fp$spousalagediff)
hist(fp$spousalagediff)

```

```{r}
#Polygamy q119

fp$q119<- as.factor(fp$q119)
typeof(fp$q119)
levels(fp[,"q119"])

fp$q119 <- factor(as.numeric(fp$q119), levels = c( '1', '2'), labels = c("Yes", "No"))


fp%>%
  group_by(q119) %>%
  count() %>%
  mutate (percent =n/nrow(fp) *100)

```

```{r}
#Familysize q121
fp$q121 <- as.numeric(fp$q121)

describe(fp$q121)
hist(fp$q121)
```

```{r}
#Familytype q122

fp$q122<- as.factor(fp$q122)
typeof(fp$q122)
levels(fp[,"q122"])

fp$q122 <- factor(as.numeric(fp$q122), levels = c( '1', '2', '3'), labels = c("Nuclear", "Joint", "Extended"))


fp%>%
  group_by(q122) %>%
  count() %>%
  mutate (percent =n/nrow(fp) *100)
```









```{r}
library(table1)

label(fp$agegroup) <- "Age"
label(fp$respcastecode) <- "Caste"
label(fp$q107) <- "Religion"
label(fp$district) <- "district"
label(fp$province) <- "Province"
label(fp$q122) <- "type of family"

table1 :: table1(~ agegroup + respcastecode + q107 + q105 + province +  q122 | q114, caption = "Summay of Demographic Statistics", data = fp)

```









```{r}
#Distance from HF 
fp$distance <- as.numeric(fp$distance)

describe(fp$distance)
hist(fp$distance)
```
```{r}
#Currentlylivingwith spouse 120a
fp$q120a<- as.factor(fp$q120a)
typeof(fp$q120a)
levels(fp[,"q120a"])

fp$q120a <- factor(as.numeric(fp$q120a), levels = c( '1', '2'), labels = c("Yes", "No"))


fp%>%
  group_by(q120a) %>%
  count() %>%
  mutate (percent =n/nrow(fp) *100)


#Duratrion since marriage
fp <- fp %>%
  mutate(marrieduration = q109-q110)
fp$marrieduration
# How long with spouse 120b (requires cleaning ; Current age < Age at marriage)


```
```{r}
#Husbandmigration

fp$migration<- as.factor(fp$migration)
typeof(fp$migration)
levels(fp[,"migration"])

fp$migration <- factor(as.numeric(fp$migration), levels = c( '1', '2', '3'), labels = c("Same district", "Different district", "Outside Nepal"))


fp %>%
  filter(migration == "Same district"  | migration == "Different district" | migration == "Outside Nepal") %>%
  group_by(migration) %>%
  count() %>%
  mutate (percent =n/nrow(fp) *100)

```
```{r}
#IWI index

#Make all the variables numeric
fp$tv <- as.numeric(fp$tv)
fp$fridge <- as.numeric(fp$fridge)
fp$phone <- as.numeric(fp$phone)
fp$twowheel<- as.numeric(fp$twowheel)
fp$threewheel <- as.numeric(fp$threewheel)
fp$cheaputen <- as.numeric(fp$cheaputen)
fp$exputen <- as.numeric(fp$exputen)
fp$electricity <- as.numeric(fp$electricity)
fp$water <- as.numeric(fp$water)
fp$toilet <- as.numeric(fp$toilet)
fp$floor<- as.numeric(fp$floor)
fp$sroom<- as.numeric(fp$sroom)

#Check the type
typeof(fp$tv)

#It is assumed that if a household has a expensive utensil, it also has a cheap utensil.
fp <- fp %>%
  mutate(cheaputen1 =  ifelse(tv == 1 | fridge == 1 | phone == 1 | twowheel == 1| threewheel == 1| exputen == 1 | toilet==3 |floor == 3 | cheaputen ==1, 1, 2))
describe(fp$cheaputen1)

#Check for "Dont know)
iwi <- fp%>%
  filter(tv != 3 & fridge != 3 & phone != 3 & twowheel != 3 & threewheel != 3 & cheaputen1 != 3 & exputen != 3 & electricity != 3 & water != 4 &  toilet != 4 & floor != 4 & sroom != 4)

nonmissing = nrow(fpiwi) #Nonmissing rows
nonmissing
missing = nrow(fp) - nrow (fpiwi) #Missing rows' number
missing

#Syntax to recode 1,2 and 3s and reassign weights
iwi <- iwi %>%
  mutate(tv1 = ifelse(tv ==1, 8.612657, 0 ))

iwi <- iwi %>%
  mutate(fridge1 = ifelse(fridge ==1, 8.429076, 0 ))

iwi <- iwi %>%
  mutate(phone1 = ifelse(phone ==1, 7.127699, 0 ))

iwi <- iwi %>%
  mutate(twowheel1 = ifelse(twowheel ==1, 1.84686, 0 ))

iwi <- iwi %>%
  mutate(threewheel1 = ifelse(threewheel ==1, 4.651382, 0))

iwi <- iwi %>%
  mutate(cheaputen2 = ifelse(cheaputen1 ==1, 4.118394, 0))

iwi <- iwi %>%
  mutate(exputen1 = ifelse(exputen ==1, 6.507283, 0))

iwi <- iwi %>%
  mutate(electricity1 = ifelse(electricity ==1, 8.056664, 0))

iwi <- iwi %>%
  mutate(water1 = ifelse(water ==1,-6.306477,
                         ifelse(water == 2, -2.302023, 7.952443)))

iwi <- iwi %>%
  mutate(toilet1 = ifelse(toilet ==1,-7.439841,
                         ifelse(water == 2, -1.090393, 8.140637)))

iwi <- iwi %>%
  mutate(floor1 = ifelse(floor ==1,-7.558471,
                         ifelse(water == 2, 1.227531, 6.107428)))


iwi <- iwi %>%
  mutate(sroom1 = ifelse(sroom ==1,-3.699681,
                         ifelse(water == 2, 0.38405, 3.445009)))


# Add a column with 25.00447 as constant
iwi$iwiconst <- 25.00447
  

#Create a new variable iwiscore
iwi <- iwi %>%
  mutate(iwiscore = tv1 + fridge1 + phone1 + twowheel1 + threewheel1 + cheaputen2 + exputen1 +electricity1 + water1 + toilet1 + floor1 + sroom1 + iwiconst)

describe(iwi$iwiscore)
ggplot(iwi)+
  aes(iwiscore)+
  geom_histogram(binwidth = 5)


#Creating a wealth quintile
library(Hmisc)

iwi$quintile <- cut2(iwi$iwiscore, g =5)

#Wealth quinitile description
iwi %>%
  group_by(quintile) %>%
  count() %>%
  mutate(percent = n/nrow(iwi)*100)


#Urban/Rural wealth quintile bar visualization
ggplot(iwi) +
  aes(typeoflocal1) +
  geom_bar(aes(fill = quintile)) +
  xlab("Residence") +
  ylab("Percentage") +
  ggtitle("Wealth distribution by Residence")

```
